- jaxley/modules/base.py
- jaxley/utils/cell_utils.py
This was also discussed in #395.
> faster compartment center updates

- jaxley/utils/cell_utils.py
- jaxley/utils/debug_solver.py
- jaxley/utils/misc_utils.py
- tests/swc_files/asc2swc.py
- tests/test_license.py
- tests/test_pickle.py
noticed that not all files had a license header so I added this to the CI.
> Add test for license header and add missing headers

- jaxley/modules/base.py
More documentation and prepare remove `nseg` from `_update_nodes_with_xyz`
> `_update_nodes_with_xyz` for heterogenous nseg

- jaxley/integrate.py
- jaxley/modules/base.py
- jaxley/modules/branch.py
- jaxley/modules/cell.py
- jaxley/modules/compartment.py
- jaxley/modules/network.py
> Make several methods private; delete unused methods

- jaxley/connect.py
> fix for `connectivity_matrix_connect` bug #486

- docs/tutorials/00_jaxley_api.ipynb
- docs/tutorials/01_morph_neurons.ipynb
- docs/tutorials/09_advanced_indexing.ipynb
- docs/tutorials/10_advanced_parameter_sharing.ipynb
- pyproject.toml
- fix broken links in tutorials
- add optax also as `doc` dependency because it is needed to run the tutorial
> fix broken links

- jaxley/modules/base.py
- jaxley/utils/cell_utils.py
- tests/test_plotting_api.py
closes #497 #510.
Fixes `xyzr` attr and how loc handles different nseg. Also ammends current tests.
> Fix issues plotting comps with different nseg

- docs/reference/jaxley.utils.rst
- docs/tutorials/09_advanced_indexing.ipynb
- mkdocs/docs/reference/utils.md
- fixes tutorials
- removes `utils.swc` from docs
> Fixup in tutorial on synapse indexing

- jaxley/io/swc.py
- jaxley/utils/cell_utils.py
While solving merge conflicts I lost some of the changes I had wanted to make in #509.
This PR fixes this, thereby also making tutorial notebooks pass.
> Fixups for SWC reader defaults

- docs/index.rst
- mkdocs/docs/index.md
- fixes for broken links
- officially deprecate the old website
> fixups for website

- .github/workflows/regression_tests.yml
Since they are currently not working, I am disabling them for the moment. See #543 for context
> disable regression tests

- .github/workflows/regression_tests.yml
- tests/test_regression.py
fixes a few small errors that I noticed when running this in #487.
> Minor fixes in regression CI

- .github/workflows/regression_tests.yml
the name annoyed me a bit, so I renamed the workflow.
> rename update to run regression tests

- CHANGELOG.md
add changes to changelog and tag to commit
> amend #580

- jaxley/__version__.py
- pyproject.toml
Way too distracted, forgot to bump version cos stupid. --> ammends #580 and #585.
> bump version, make release

- CHANGELOG.md
- jaxley/synapses/ionotropic.py
expose `delta` and `v_tresh` for `IonotropicSynapse`.
> make ionotropic more flexible

- CHANGELOG.md
- jaxley/optimize/transforms.py
I found this minor bug in ChainTransform so I'll submit this PR. Not sure if this requires updating the changelog, additional testing and the whole nine yards, but if so I might have to either have someone else do that or get back to it in a few weeks. 
Edit: I updated the changelog but didn't add tests, for my own personal use it works though
> Fixed minor bug/typo in ChainTransform

- jaxley/modules/base.py
- tests/test_make_trainable.py
> Fix data set indices

- CHANGELOG.md
- docs/jaxley.rst
- jaxley/synapses/__init__.py
- jaxley/synapses/conductance.py
- jaxley/synapses/tanh_conductance.py
- tests/test_synapse_indexing.py
This additional synapse is mainly for my own use, but we talked about adding it here because it's quite generic and therefore might be useful to others. I can also relocate it though if anyone objects.
> Conductance synapse addition

- CHANGELOG.md
- docs/examples.rst
- docs/examples/00_l5pc_gradient_descent.ipynb
- docs/index.rst
- jaxley/connect.py
This PR creates a new `Examples` section on the website.
I am planning to port several of the paper examples to this section.
> Add an example notebook on fitting an L5PC
