jaxley/utils/cell_utils.py

fixes:
```
jaxley/jaxley/utils/cell_utils.py:235: SyntaxWarning: invalid escape sequence '\s'
"""Return the coupling conductance between one compartment and a comp with l=0.
jaxley/jaxley/utils/cell_utils.py:258: SyntaxWarning: invalid escape sequence '\p'
"""Compute the weight with which a compartment influences its node.
```
on import of jaxley

fix warnings on import of cell_utils for invalid escape char

---

.github/workflows/build_docs.yml
.gitignore
docs/mkdocs.yml
pyproject.toml

[mike](https://github.com/jimporter/mike) allows us to have different docs versions in parallel
we want to have one `dev` version showing the docs of the `main` branch (unreleased), and one latest version showing the docs of the `latest` release
the website docs should always show the latest version
whenever we push to main, the `dev` version is updated:
`tutorial` notebooks are converted into markdown and the docs files are created using `mkdocs build`
whenever we publish a new release, the same thing happens, but the latest docs is updated (`-u` option in the command) to the new release and deployed on the website.

Add release versioning with mike

---

jaxley/integrate.py
jaxley/modules/base.py
jaxley/solver_voltage.py
tests/jaxley_vs_neuron/test_branch.py
tests/jaxley_vs_neuron/test_cell.py
tests/jaxley_vs_neuron/test_comp.py
tests/test_solver.py
tests/test_swc.py

This PR fixes forward Euler solvers and also implements a Cranck Nicolson solver.
Forward Euler raises for branched cells (or networks thereof).

Forward Euler and Cranck Nicolson solvers

---

jaxley/utils/cell_utils.py

This avoids issues with compartments (e.g. somas) that are traced with a single point.

Add epsilon to branch_len

---

jaxley/channels/hh.py
jaxley/channels/pospischil.py
jaxley/modules/base.py

To use jaxley-mech after this, we have to merge [this](https://github.com/jaxleyverse/jaxley-mech/pull/42) PR in Jaxley-Mech.

Add option to use states in `init_state`

---

tutorials/01_morph_neurons.ipynb
tutorials/02_small_network.ipynb
tutorials/03_setting_parameters.ipynb
tutorials/04_jit_and_vmap.ipynb
tutorials/05_channel_and_synapse_models.ipynb
tutorials/06_groups.ipynb
tutorials/07_gradient_descent.ipynb
tutorials/08_importing_morphologies.ipynb

Without this, one gets lost in an old version of the docs if one follows the links in the tutorials (I don't exactly know why to be honest).

Add /latest to all links in tutorials

---

jaxley/build_branched_tridiag.py
jaxley/integrate.py
jaxley/modules/base.py
jaxley/modules/branch.py
jaxley/modules/cell.py
jaxley/modules/compartment.py
jaxley/modules/network.py
jaxley/solver_voltage.py
jaxley/utils/cell_utils.py
jaxley/utils/debug_solver.py
tests/jaxley_identical/test_basic_modules.py
tests/jaxley_identical/test_radius_and_length.py
tests/jaxley_vs_neuron/test_cell.py
tests/test_api_equivalence.py
tests/test_make_trainable.py

This PR enables that every branch can have a different number of compartments.
```python
comp = jx.Compartment()
branch1 = jx.Branch(comp, nseg=1)
branch2 = jx.Branch(comp, nseg=2)
branch3 = jx.Branch(comp, nseg=3)
cell = jx.Cell([branch1, branch2, branch3], parents=[-1, 0, 0])
cell.insert(HH())
cell.branch(1).comp(1).stimulate(jx.step_current(0.5, 1.0, 0.1, 0.025, 5.0))
cell.branch(0).comp(0).record()
voltages = jx.integrate(cell, delta_t=dt, voltage_solver="jax.sparse")
```
This is achieved by:
1) Building infrastructure to deal with a different number of compartments and
2) relying on `jax.experimental.sparse.spsolve` as a generic solver.
With this PR, we are now supporting `jx.integrate(..., voltage_solver="jax.sparse")`. This uses the generic [sparse solver of …

Allow different nseg per branch and add `jax.sparse` solver

---

jaxley/modules/base.py
jaxley/modules/compartment.py
jaxley/utils/plot_utils.py
tests/test_plotting_api.py

I got side-tracked while working on a different PR and implemented plotting of the actual compartment structure:
The compartments are rendered in 3D and then the correct projection of the 3d mesh is plotted on whatever plane. 
```
fig, ax = plt.subplots(2, 3, figsize=(10, 5))
for i, orientation in enumerate([np.array([1,1,2]), np.array([0,1,0.1]), np.array([0,0.1,1])]):
plot_cylinder_projection(orientation, length=5, radius=1, center=np.array([0,0,0]), dims=[0,1], ax=ax[0,i])
plot_cylinder_projection(orientation, length=5, radius=1, center=np.array([0,0,0]), dims=[1,2], ax=ax[1,i])
ax[0,i].set_title(f"Orientation: {orientation}")
plt.show()
```
Hence the compartment radii and lengths are correctly reflected in the plot.
However, plotting an imported morphology looked weird for some …

Plotting of comp morphology

---

jaxley/modules/base.py
jaxley/modules/branch.py
jaxley/modules/cell.py
jaxley/modules/compartment.py
jaxley/modules/network.py
jaxley/utils/misc_utils.py
jaxley/utils/swc.py
tests/test_set_ncomp.py

This PR is a follow-up to #418 and #426. It allows to set `nseg` **after** initialization of the module. This is achieved with a new `set_ncomp` method. This PR is the final requirement for a new release with these features.
Works for branches:
```python
comp = jx.Compartment()
branch = jx.Branch(comp, nseg=2)
branch.set_ncomp(4)
```
...for branches within a cell:
```python
comp = jx.Compartment()
branch = jx.Branch(comp, nseg=2)
cell = jx.Cell(branch, parents=[-1, 0, 0])
cell.branch(1).set_ncomp(4)
```
...and for branches read from SWC files, in which case it reuses the xyzr to compute optional radiuses:
```python
cell = jx.read_swc(fname, nseg=2)
cell.branch(1).set_ncomp(4)
```
The `set_ncomp` function will raise an error if:  
- There are stimuli in **any** compartment in the module …

Allow changing nseg after initialization

---

jaxley/connect.py
jaxley/modules/base.py
jaxley/modules/branch.py
jaxley/modules/compartment.py
jaxley/utils/cell_utils.py
tests/test_connection.py
tests/test_groups.py
tests/test_indexing.py

This PR contains final fixes for having heterogenous numbers of compartments in different branches. It does the following things:
- update `index_of_loc`
- update `loc_of_index`
- remove `_local_inds_to_global` (which could easily be replaced in the __one__ place where it was used)
Replaces #439

Fixups for having heterogenous numbers of compartments in each branch

---

jaxley/synapses/test.py
jaxley/utils/jax_utils.py
tests/test_groups.py

We change all:
- jax.tree_map -> jax.tree_util.tree_map
- Pytest ignores TestSynapse
Note: We do not change use of `a_max` in `jnp.clip`, because this require jax>0.4.30 (which is too recent yet)

Reduce warnings

---

jaxley/integrate.py
tests/test_api_equivalence.py

Currently, the only user API to solve a cell ODE is `jx.integrate`. For various applications, it is useful to have access to an `init` function, which initializes the state, and a `step` function, which executes a single ode step. Some examples are:
- Nonuniform step sizes
- Integration with Kalman or Particle filtering frameworks
- Stochastic Models (i.e. add noise after each step) ...
Also see #350 .
```python
init_fn, step_fn = build_init_and_step_fn(cell, **maybe_some_other)
states, params = init_fn(params, all_states, **kwargs)
next_state = step_fn(states, params, externals, dt=0.025, **kwargs)
```

User exposing init and step for customization.

---

jaxley/modules/base.py
tests/test_make_trainable.py

This PR introduces a `write_trainables()` which adds the trainables to the `.nodes` and `.edges` such that they can be used for plotting, printing,...
```python
net.make_trainable("radius")
params = net.get_parameters()
net.write_trainables(params)
```
Closes #356

Write trainables to module

---

jaxley/modules/base.py
jaxley/modules/network.py
tests/test_connection.py
tests/test_groups.py
tests/test_viewing.py

The following is a copy of the remaining todos from #447
> Merging this will make https://github.com/jaxleyverse/jaxley/pull/329, https://github.com/jaxleyverse/jaxley/pull/330, https://github.com/jaxleyverse/jaxley/pull/351 obsolete and close https://github.com/jaxleyverse/jaxley/issues/377, https://github.com/jaxleyverse/jaxley/issues/354, probably https://github.com/jaxleyverse/jaxley/issues/338 and I guess also https://github.com/jaxleyverse/jaxley/issues/133
> Will also make https://github.com/jaxleyverse/jaxley/issues/264 and https://github.com/jaxleyverse/jaxley/issues/134 trivial
> Also might wanna revisit https://github.com/jaxleyverse/jaxley/issues/291 after this
> ### Comments:
> - Moved `_append_multiple_synapses` and associated functionality to `Network`.
> - `SynapseView` …

Continuing better Viewing (#447)

---

tests/test_data_feeding.py

adds tests for data_stimulate + jist + trainable_params case.
closes #467.

include trainable params in data_stimulate tests

---

jaxley/utils/plot_utils.py
tests/test_plotting_api.py
tests/test_swc.py

Main contributions:
- swc tests now significantly faster (change to sparse solver)
- plotting tests a lot faster
- exposed 'resolution' of mesh generation (no proper exposition to user (yet)) fixes #468
- splitted plot volume test for more granular analysis
minor contributions:
- added test fixtures for compartment, cell, morph_cell, branch and network -> not sure how much it helps / improves readability here. Could also revert these changes. (might be a first step for #449)

Speed up tests (swc, plotting)

---

jaxley/modules/base.py
jaxley/modules/branch.py
jaxley/modules/cell.py
jaxley/modules/compartment.py
jaxley/modules/network.py
tests/test_viewing.py

Closes #448
@michaeldeistler @jnsbck is the list of methods/attributes to make private actually agreed upon? Here's what was stated int he issue:
```
"par_inds",
"child_inds",
"child_belongs_to_branchpoint",
"solve_indexer",
"cells_list",
"cumsum_nbranchpoints_per_cell",
"cumsum_nbranches"
```
I've started with `par_inds` to get a feel for the code base, but I'll wait for you input before continuing

[MRG] Make methods/attributes private

---

jaxley/modules/base.py
tests/test_viewing.py

This PR adds boolean indexing to Views. This is for convenience. Can be used to do stuff like:
```python
r_greater_1 = net.nodes.groupby("global_cell_index)["r"].mean() > 1
net[r_greater_1].nodes.vis()
net.select(nodes=net.nodes["r"] > 1) # vs. net.select(nodes=net.nodes.index[net.nodes["r"] > 1])
```

Add support for boolean indexing of cells/branches/comps

---

jaxley/modules/base.py
tests/test_channels.py

This PR adds an `uninsert` method. 
I find the name a bit wonky tbh. Was also wondering if we should add a `disconnect` method to `connect.py`.
todos:

add uninsert method

---

jaxley/__init__.py
jaxley/io/swc.py
jaxley/modules/__init__.py
jaxley/modules/base.py
jaxley/modules/cell.py
jaxley/utils/cell_utils.py
tests/conftest.py

I think it makes more sense to have the swc reader in a dedicated IO module and not in `modules/cell.py`.

Move `read_swc.py` to `io`

---

docs/faq/question_03.md
docs/faq/question_04.md

Add FAQ about rate-based networks

---

CHANGELOG.md
jaxley/modules/base.py
jaxley/modules/network.py
tests/test_record_and_stimulate.py

Closes #363 and #533
As discussed with @jnsbck in #515, this PR adds `synapse_current_names` as an attribute to the base module, and then appends this to the synapse states in `_get_state_names()`. The end goal is for currents to be recordable via:
```py
net.record('IonotropicSynapse_current')
```
Some lingering thoughts:
1) Is it worth changing "current" to "i" for consistency with the channel naming conventions?
2) It took me awhile to figure out that I needed to modify the `View` class. Will it be necessary to add a `self._synapses_in_view()` property for this to work properly?
3) Add some tests that check basic assumptions of the current recording?

[MRG] Add ability to record synaptic currents

---

.github/workflows/update_regression_baseline.yml
.gitignore
tests/conftest.py
tests/test_regression.py

Regression is now evaluated with a single sample t-test, i.e. the baseline times = conf bounds. This is much nicer imo and giving a confidence region for tests to pass should also make it more robust to potential runtime fluctuations on the github runners.
Also made a few smaller follow up fixes for #475.

Confidence bounds for regression tests

---

CHANGELOG.md
jaxley/modules/base.py
jaxley/modules/network.py
jaxley/utils/plot_utils.py
pyproject.toml
tests/test_plotting_api.py

Fixes #465 and refactors some plotting functionality. 
Changes:
- rm `morph_plot_kwargs`, rely on `**kwargs` instead.
- renamed kwarg `"col"` -> `"color"` for consistency with pyplot.
- Refactor `Network.vis`
- cleanup of code (use new View functionality) and removal of unnecessary kwargs
- rm `_to_graph` since it is obsolete now (replaced by scatter, which might be not as nice as the graph plotting, can be added back in though.). Since networkx is not used currently, this could also be removed as a dependency (until #355 makes it in at least)
- disentangle moving and visualizing of cells, by adding `arrange_in_layers`. I think this is more clear and seperates out the additional kwargs of `vis`.
To get the same as `net.vis(layers=[3,3])` one now has to do.
```python …
```

Small refactor of plotting

---

jaxley/modules/network.py

```python
branch = jx.Branch(nseg=10)
cell = jx.Cell([branch]*3, [-1,0,0])
net = jx.Network([cell]*6)
net.compute_xyz()
net.arrange_in_layers([3, 3])
fully_connect(net[:3], net[3:], IonotropicSynapse())
net.vis()
```
looks like this again now.

highlight synapse_terminals in plotting

---

CHANGELOG.md
jaxley/modules/base.py
tests/test_make_trainable.py

This PR attempts to enable param sharing for controll groups with different numbers of members. This can be important for sharing params between branches with different numbers of segments or edges with different numbers of pre synaptic cells (see #501).
This also fixes #501.
todos:

Enable param sharing with differently sized groups

---

CHANGELOG.md
jaxley/__init__.py
jaxley/__version__.py
pyproject.toml

I realized that:
```python
import jaxley as jx
print(jx.__version__)
```
had not been possible due to the missing import.

Prepare release; allow easy access of version

---

.readthedocs.yaml
CHANGELOG.md

The most recent readthedocs documentation (v0.6.0) did not build because we now require an explicit reference to the sphinx config file. See [here](https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/) for more info.
With this change, v0.6.1 should build successfully.

Make sphinx configuration file explicit

---

CHANGELOG.md
jaxley/__version__.py
jaxley/io/graph.py
jaxley/io/swc.py
jaxley/modules/branch.py
pyproject.toml
tests/helpers.py
tests/test_graph.py
tests/test_make_trainable.py
tests/test_misc.py
tests/test_pickle.py
tests/test_regression.py

Deprecation helper should have raised when bumping the version, but did not trigger. This fixes that, deprecates nseg and bumps the version to `0.6.1`.

deprecate nseg and bump version

---

.github/workflows/make_release.yml
CHANGELOG.md

first draft of a release workflow with the following idea:
once a PR is labelled with `release`, it runs additional checks if version numbers have been incremented and the changelog has been updated. On push to `main`, we tag the commit, build the wheel, publish it to pypi and make a github release with the latest changes.

add automatic release workflow

---

CHANGELOG.md
jaxley/channels/__init__.py
jaxley/channels/lif.py

Added a simple LIF channel and also one that is potentially differentiable, although I have not tested this.
Probably needs some tests and scrutiny.

LIF Channel

---

CHANGELOG.md
jaxley/modules/base.py
tests/test_distance.py

The following does not work in `JAX`:
```python
@jit
def mytest(param):
return np.sqrt(np.sum(param * np.asarray([3.0, 4.0])))
mytest(jnp.ones((1,)))
```
To make this work, one needs:
```python
@jit
def mytest(param):
return jnp.sqrt(jnp.sum(param * np.asarray([3.0, 4.0])))
mytest(jnp.ones((1,)))
```
This caused our `.distance()` to break within a `jit`. This PR fixes it.

Allow `.distance` to be jitted

---

CHANGELOG.md
docs/tutorials/11_ion_dynamics.ipynb
jaxley/modules/base.py

The assert within `get_all_parameters()` broke because this function gets `jit`ted. We now move the assert to `.set()`. This might cause issues if the user uses `data_set()`, but I also left a very vocal warning on the tutorial notebook.
JAX's `checkify` did not work out of the box.

Bugfix: allow ion diffusion to be jitted

---

CHANGELOG.md
jaxley/modules/base.py
jaxley/modules/branch.py
jaxley/modules/cell.py
jaxley/modules/compartment.py
jaxley/modules/network.py
jaxley/utils/cell_utils.py
tests/test_viewing.py

After this PR, `._comp_edges` gets updated in `View`:
```python
cell.branch(1).loc(0.0)._comp_edges
```
This PR also introduces a few special rules for this:
- for `cell.branch(1)` all edges to neighboring branchpoints are included.
- for `cell.branch(1).comp(0)` no edges to branchpoints are included.
- for `cell.branch(1).loc(0.0)` edges to the parent branchpoint are included.
- for `cell.branch(1).loc(1.0)` edges to the child branchpoint are included.
Why do we need these special rules? For modifying a morphology, we need some method to indicate to which end of a branch we want to attach another morphology. Consider the case where all branches have 1 compartment. Then:
`morph_attach(cell.branch(0).comp(0), new_morph)` would not know whether to attach the `new_morph` at the end or at the …

View tracks ._comp_edges

---

CHANGELOG.md
jaxley/modules/base.py
jaxley/modules/network.py
tests/test_synapse_indexing.py

The test added in this pull request used to fail because the rec_index came from `self._edges_in_view` (indices from the whole edges dataframe) while jaxedges saves synapse states separately by synapse type (thanks for your investigation @michaeldeistler!). This then means that synapse states returned as the recordings were incorrect if their global edge index exceeded the number of edges of that synapse type. In this case the recording would have mirrored the last synapse state timecourse within range.
People who use multiple synapse types and record synapse states would have been strongly affected.

Synapse recording indices bug fix

---

CHANGELOG.md
jaxley/modules/base.py
tests/test_viewing.py

Fixes #590 and adds test to check for this in the future. 
I tried to avoid adding more attributes to the module class. The simpler solution would have been to add a `name` attr to each `Module` that could have been checked and is not overwritten by class inheritance like `__class__.__name__`. 
If you prefer this let me know.

fix how `_current_view` is determined

---

CHANGELOG.md
docs/jaxley.rst
docs/tutorials/08_importing_morphologies.ipynb
jaxley/modules/base.py
jaxley/morphology/__init__.py
jaxley/morphology/distance_utils.py
jaxley/morphology/morph_utils.py
tests/test_distance.py

Closes #572 
- deprecate `module.distance()`. It is replaced by `jx.morphology.distance_direct()`
- introduce `jx.morphology.distance_pathwise()`
- the new `distance_pathwise()` allows users to compute pathwise distance.
Example 1: The following computes the pathwise distance between the zero-eth soma compartment and all other compartments. It then saves this distance in
`cell.nodes["path_dist_from_soma"]`.
```python
from jaxley.morphology import distance_pathwise
path_dists = distance_pathwise(cell.soma.branch(0).comp(0), cell)
cell.nodes["path_dist_from_soma"] = path_dists
```
Example 2: The following computes the pathwise distance between two compartments.
```python
from jaxley.morphology import distance_pathwise
dist = distance_pathwise(cell.branch(8).comp(2), cell.branch(2).comp(0)) …
```

Pathwise distance between compartments

---

CHANGELOG.md
jaxley/modules/base.py
jaxley/modules/compartment.py
jaxley/modules/network.py
jaxley/utils/solver_utils.py
mkdocs/README.md
tests/jaxley_identical/test_basic_modules.py
tests/jaxley_identical/test_swc.py
tests/test_regression.py

Only for networks of multicompartment neurons (not point neurons), and only on GPU, our solver has been extremely suboptimal since `Jaxley` version `0.9.0`, following [this PR](https://github.com/jaxleyverse/jaxley/pull/625).
This is due to a bug which caused the voltages of cells to be processed sequentially, instead of in parallel (If they are multicompartment). This PR provides a minimal fix for this.
There are no breaking changes for the API. However, this PR introduces a new keyword argument to the `Network`:
```python
net = jx.Network([cell], vectorize_cells=True)
```
When set to `True`, we automatically use the gpu-based solver and we parallelize across cells. This is the default on GPU. The default on CPU is `False` because it optimizes compile time (and barely affects runtime on …

Bugfix for solver speed for networks on GPU

---

CHANGELOG.md
jaxley/channels/channel.py
jaxley/channels/hh.py
jaxley/channels/pospischil.py
jaxley/integrate.py
jaxley/modules/base.py
jaxley/modules/network.py
jaxley/optimize/optimizer.py
jaxley/optimize/transforms.py
jaxley/pumps/ca_pump.py
jaxley/pumps/faraday_electrolysis.py
jaxley/pumps/pump.py
jaxley/solver_gate.py
jaxley/solver_voltage.py
jaxley/synapses/synapse.py
jaxley/utils/cell_utils.py
jaxley/utils/debug_solver.py
jaxley/utils/jax_utils.py
jaxley/utils/morph_attributes.py
jaxley/utils/solver_utils.py
jaxley/utils/syn_utils.py
tests/test_channels.py
tests/test_ion_diffusion_and_pumps.py
tests/test_shared_state.py

Fixes/implements #469 
Note that additional non-jax typing changed were made, however these changes were only made on the same lines where the jax related typing changes were made. The changes are mostly using Python native types (list, dict, tuple, etc.) instead of types from the typing package (List, Dict, Tuple, etc.). Using Python native types has been standard since Python 3.9, so I hope these additional changes are also okay, since Jaxley claims to require Python>=3.10 anyway.

Follow Jax Typing Practices

---

CHANGELOG.md
jaxley/modules/base.py
tests/test_groups.py

Fixup for things like:
```python
cell1 = jx.Cell()
cell1.add_to_group("soma")
cell2 = jx.Cell()
cell2.add_to_group("axon")
net = jx.Network([cell1, cell2])
net.soma
```

Carry over groups from constituents of a module

---

CHANGELOG.md
jaxley/modules/base.py
tests/test_channels.py

To reproduce the error:
```python
from jaxley.channels import HH
comp = jx.Compartment()
branch = jx.Branch(comp, ncomp=2)
cell1 = jx.Cell(branch, [-1, 0, 1])
cell2 = jx.Cell(branch, [-1, 0, 1, 2])
cell3 = jx.Cell(branch, [-1, 0])
net = jx.Network([cell1, cell2, cell3])
net.cell(0).branch(1).add_to_group("apical")
net.cell(1).branch(3).add_to_group("apical")
net.cell(2).branch(1).add_to_group("apical")
net.apical.insert(HH())
net.init_states()
```
The reason that this bug happened is that `init_states` was still using the `global_comp_index`, instead of the `index` (as is done in `step_channels`).

Bugfix for indexing in `init_states` for networks

---

CHANGELOG.md
jaxley/modules/base.py
tests/test_channels.py

Currently, `.delete()` deletes the `current_name` when a channel is deleted, even if another channel also has that same `current_name`. Same for shared parameters or shared states.
This PR fixes this.

Fixup for `.delete()` when multiple channels have the same current_name
